"""
Django settings for sharelibrary project.
Generated by 'django-admin startproject' using Django 3.0.3.
For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from .base import *  # NOQA

DEBUG = True



# Application definition

INSTALLED_APPS += [
]

MIDDLEWARE += [
]