# Generated by Django 3.0.5 on 2020-05-10 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('douban_book_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=10)),
                ('publisher', models.CharField(max_length=50)),
                ('pubdate', models.CharField(max_length=10)),
                ('translator', models.CharField(max_length=200)),
                ('douban_small_image_url', models.URLField()),
                ('image_url', models.URLField(default='')),
                ('rating_number', models.IntegerField(default=0)),
                ('rating_average', models.SmallIntegerField(default=0)),
                ('tags', models.CharField(max_length=50)),
                ('isbn10', models.CharField(max_length=10)),
                ('isbn13', models.CharField(max_length=13)),
                ('url', models.URLField()),
                ('catalog', models.TextField()),
                ('author_intro', models.TextField()),
                ('summary', models.TextField()),
                ('price', models.CharField(default='', max_length=15)),
                ('pages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
