# Generated by Django 3.0.5 on 2020-05-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('douban_book_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=10)),
                ('publisher', models.CharField(max_length=50)),
                ('pubdate', models.CharField(max_length=10)),
                ('translator', models.CharField(max_length=200)),
                ('image_small', models.URLField()),
                ('rating_number', models.IntegerField(default=0)),
                ('rating_average', models.SmallIntegerField(default=0)),
                ('tags', models.CharField(max_length=50)),
                ('isbn10', models.CharField(max_length=10)),
                ('isbn13', models.CharField(max_length=13)),
                ('url', models.URLField()),
                ('catalog', models.TextField()),
                ('author_intro', models.TextField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
