# Generated by Django 3.0.5 on 2020-06-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owners',
            field=models.ManyToManyField(to='shelfs.UserProfile'),
        ),
    ]
