# Generated by Django 3.0.5 on 2020-06-07 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelfs', '0002_auto_20200607_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
