# Generated by Django 3.0.5 on 2020-05-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
