# Generated by Django 3.0.5 on 2020-05-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0003_book_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_small',
            new_name='douban_small_image_url',
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
