# Generated by Django 3.0.5 on 2020-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0003_auto_20200607_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owners',
            field=models.ManyToManyField(to='shelfs.UserProfile'),
        ),
    ]
